language: node_js # 项目语言，node 项目就按照这种写法就OK了
node_js:
  - 12.20.1 # 项目环境
cache: # 缓存 node_js 依赖，提升第二次构建的效率
  directories:
    - node_modules

install:
  - npm install

test:
  - npm run test # 运行自动测试框架

after_success: # 构建成功后的自定义操作
  - npm run codecov # 生成 Github 首页的 codecov 图标
